# Generated by Django 3.0 on 2020-09-16 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200916_1933'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_description',
            field=models.CharField(default='', max_length=2000),
        ),
        migrations.AddField(
            model_name='user',
            name='role_in_school',
            field=models.CharField(choices=[('TR', 'Teacher'), ('ST', 'Student')], default='ST', max_length=2),
        ),
    ]
